inherit_gem:
  citizens-advice-style:
    - default.yml

# Calls to super in subclasses of ViewComponent::Base aren't needed
# by default and can change the behaviour of **kwargs so we
# exclude component classes from this rule
# https://github.com/ViewComponent/view_component/discussions/1545
Lint/MissingSuper:
  Exclude:
    - 'src/_components/**/*'
