# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Hello! This is where you manage which Bridgetown version is used to run.
# When you want to use a different version, change it below, save the
# file and run `bundle install`. Run Bridgetown like so:
#
#   bin/bridgetown start (or console, etc.)
#
# This will help ensure the proper Bridgetown version is running.
#
# To install a plugin, simply run bundle add and specify the group
# "bridgetown_plugins". For example:
#
#   bundle add some-new-plugin -g bridgetown_plugins
#
# Happy Bridgetowning!

gem "bridgetown", "~> 1.0"

# Puma is a Rack-compatible server
# (you can optionally limit this to the "development" group)
gem "puma", "~> 5.2"

# citizens advice design system view components
gem "citizens_advice_components", path: "../engine"

group :bridgetown_plugins do
  gem "bridgetown-view-component", "~> 1.0"
end

group :development, :test do
  gem "citizens-advice-style",
      github: "citizensadvice/citizens-advice-style-ruby",
      tag: "v7.0.0"
end
