# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Hello! This is where you manage which Bridgetown version is used to run.
# When you want to use a different version, change it below, save the
# file and run `bundle install`. Run Bridgetown like so:
#
#   bin/bridgetown start (or console, etc.)
#
# This will help ensure the proper Bridgetown version is running.
#
# To install a plugin, simply run bundle add and specify the group
# "bridgetown_plugins". For example:
#
#   bundle add some-new-plugin -g bridgetown_plugins
#
# Happy Bridgetowning!

gem "bridgetown", "~> 1.3"
gem "htmlbeautifier"
gem "nokogiri"
gem "puma", "~> 5.6"

gem "citizens_advice_components", path: "../engine"

# ViewComponent contained an error when used with bridgetown
# between versions  v2.75.0  and  v2.81.0. Make sure we are using a version
# that includes https://github.com/ViewComponent/view_component/pull/1626
# Original issues: https://github.com/bridgetownrb/bridgetown-view-component/issues/3
gem "view_component", "~> 2.82.0"

group :bridgetown_plugins do
  gem "bridgetown-seo-tag"
  gem "bridgetown-view-component", "~> 1.0"
end

group :development, :test do
  gem "citizens-advice-style",
      github: "citizensadvice/citizens-advice-style-ruby",
      tag: "v9.0.0"
end
