version: 2
updates:
  # GitHub actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    cooldown:
      default-days: 7

  # npm top-level package
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    groups:
      # Group everything except major version updates and security vulnerabilities
      regular-updates:
        update-types:
          - "minor"
          - "patch"

  # npm sub-projects
  - package-ecosystem: npm
    directories:
      - "/demo"
      - "/website"
      - "/engine"
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
    groups:
      # Group everything except major version updates and security vulnerabilities
      regular-updates:
        group-by: dependency-name
        update-types:
          - "minor"
          - "patch"

  # bundler sub-projects
  - package-ecosystem: bundler
    directories:
      - "/demo"
      - "/website"
      - "/engine"
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
    groups:
      # Group everything except major version updates and security vulnerabilities
      regular-updates:
        group-by: dependency-name
        update-types:
          - "minor"
          - "patch"
