linters:
  LineLength:
    enabled: false

  ClassesBeforeIds:
    EnforcedStyle: 'id'

  SpaceInsideHashAttributes:
    enabled: false

  UnnecessaryStringOutput:
    enabled: false

  RuboCop:
    enabled: true

    # @TODO: Gradually turn this on for all haml files
    exclude:
      - 'haml/_contact_details.html.haml'
      - 'haml/_navigation.html.haml'
      - 'haml/_notice_banner.html.haml'
      - 'haml/_page_review.html.haml'
      - 'haml/_table.html.haml'
      - 'styleguide/**/**.haml'
