linters:
  LineLength:
    enabled: false

  ClassesBeforeIds:
    EnforcedStyle: 'id'

  SpaceInsideHashAttributes:
    enabled: false

  UnnecessaryStringOutput:
    enabled: false

  RuboCop:
    enabled: true

    # @TODO: Gradually turn this on for all haml files
    exclude:
      - 'haml/_asset_hyperlink.html.haml'
      - 'haml/_breadcrumb.html.haml'
      - 'haml/_callout.html.haml'
      - 'haml/_contact_details.html.haml'
      - 'haml/_navigation.html.haml'
      - 'haml/_notice_banner.html.haml'
      - 'haml/_oisc_warning.html.haml'
      - 'haml/_page_review.html.haml'
      - 'haml/_related_content_advisernet.html.haml'
      - 'haml/_search.html.haml'
      - 'haml/_table.html.haml'
      - 'haml/_targeted-content.html.haml'
      - 'styleguide/**/**.haml'

    ignored_cops:
      # These cops are noisy when it comes to HAML templates, so we ignore them
      - Layout/TrailingEmptyLines
      - Style/FrozenStringLiteralComment

      # These cops should eventually get enabled
      - Naming/VariableName
