require: rubocop-rake

inherit_gem:
  citizens-advice-style:
    - default.yml

AllCops:
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'demo/node_modules/**/*'

Style/ClassAndModuleChildren:
  Exclude:
    # Monkey patch for Firefox driver, should eventually be removed
    - 'testing/features/support/core_ext/capybara/selenium/driver/firefox_driver.rb'

Style/MixinUsage:
  Exclude:
    - 'scripts/haml.rb'

Metrics/MethodLength:
  Exclude:
    - 'scripts/haml.rb'
    - 'testing/features/support/drivers/browserstack/base.rb'

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - 'engine/spec/**/*.rb'
    - 'demo/spec/**/*.rb'
