#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

echo_task() {
  printf "\033[0;34m--> %s\033[0m\n" "$*"
}

cd "$(dirname "$0")"

function check_npm_package() {
  echo_task "Checking npm package"
  npm run lint
  npm test
}

function check_engine() {
  echo_task "Checking Rails engine"
  pushd engine
  bundle exec rubocop
  bundle exec erb_lint --lint-all
  bundle exec appraisal rake spec
  popd
}

function check_demo_app() {
  echo_task "Checking demo app"
  pushd demo
  bundle exec rubocop
  bin/rails cypress:run
  npm run backstop:local
  popd
}

function check_docs() {
  echo_task "Checking docs"
  pushd website
  bundle exec rubocop
  bundle exec erb_lint --lint-all
  bin/static-build
  popd
}

echo_task "Checking all components"
check_npm_package
check_engine
check_demo_app
check_docs
echo_task "Checks complete!"
