version: "3"

services:
    ca-styleguide:
        build: .
        image: "ca-styleguide_${CA_STYLEGUIDE_VERSION_TAG}"
        container_name: ca-styleguide.test
        command: npm run styleguide:ci -- --quiet
        hostname: ca-styleguide.test
        ports:
            - 6006
        environment:
            - NODE_ENV=development

    visual-tests:
        build:
            dockerfile: ./testing/Dockerfile
            context: ./
        image: "ca-backstop_${CA_STYLEGUIDE_VERSION_TAG}"
        container_name: visual-tests.test
        command: wait-for-it --timeout=120 --strict ca-styleguide.test:6006 -- backstop test --config=backstop-ci.json
        volumes:
            - ./testing:/src
        depends_on:
            - ca-styleguide
