version: "3"

services:
  ca-styleguide:
    build: .
    image: "ca-styleguide${CA_STYLEGUIDE_VERSION_TAG}"
    container_name: ca-styleguide.test
    command: npm run styleguide:ci
    ports:
      - "6006:6006"
    tmpfs: /app/tmp
    user: root
    volumes:
      - .:/app
      - app-node_modules:/app/node_modules
    environment:
      - NODE_ENV=development

volumes:
  app-node_modules: {}