version: '3.2'

services:
  ca-styleguide:
    build:
      context: ./
      dockerfile: ./Dockerfile
      cache_from:
        - '979633842206.dkr.ecr.eu-west-1.amazonaws.com/design-system:dev_story-server_${CA_STYLEGUIDE_VERSION_TAG}'
        - '979633842206.dkr.ecr.eu-west-1.amazonaws.com/design-system:story-server'
    image: '979633842206.dkr.ecr.eu-west-1.amazonaws.com/design-system:dev_story-server_${CA_STYLEGUIDE_VERSION_TAG}'
    container_name: ca-styleguide.test
    command: npm run styleguide:ci -- --quiet
    hostname: ca-styleguide.test
    ports:
      - 6006:6006
    environment:
      - NODE_ENV=development

  visual-tests:
    build:
      dockerfile: ./testing/Dockerfile
      context: ./
      cache_from:
        - '979633842206.dkr.ecr.eu-west-1.amazonaws.com/design-system:dev_backstop_${CA_STYLEGUIDE_VERSION_TAG}'
        - '979633842206.dkr.ecr.eu-west-1.amazonaws.com/design-system:backstop'
    image: '979633842206.dkr.ecr.eu-west-1.amazonaws.com/design-system:dev_backstop_${CA_STYLEGUIDE_VERSION_TAG}'
    container_name: visual-tests.test
    command: wait-for-it --timeout=120 --strict ca-styleguide.test:6006 -- backstop test --config=backstop-config-ci.js
    volumes:
      - ./testing/visual-regression:/src
    depends_on:
      - ca-styleguide

  wcag-tests:
    build:
      context: ./
      dockerfile: ./testing/Dockerfile.wcag
      cache_from:
        - '979633842206.dkr.ecr.eu-west-1.amazonaws.com/design-system:dev_wcag_${CA_STYLEGUIDE_VERSION_TAG}'
        - '979633842206.dkr.ecr.eu-west-1.amazonaws.com/design-system:wcag'
    image: '979633842206.dkr.ecr.eu-west-1.amazonaws.com/design-system:dev_wcag_${CA_STYLEGUIDE_VERSION_TAG}'
    container_name: wcag-tests.test
    command: wait-for-it --timeout=120 --strict ca-styleguide:6006 -- pa11y-ci --config=/src/wcag/pa11yci.ci.js
    volumes:
      - ./testing:/src
    depends_on:
      - ca-styleguide

  cucumber: &cucumber_default
    build:
      context: ./
      dockerfile: ./testing/Dockerfile.cucumber
      cache_from:
        - '979633842206.dkr.ecr.eu-west-1.amazonaws.com/design-system:dev_ruby_${CA_STYLEGUIDE_VERSION_TAG}'
        - '979633842206.dkr.ecr.eu-west-1.amazonaws.com/design-system:ruby'
    image: '979633842206.dkr.ecr.eu-west-1.amazonaws.com/design-system:dev_ruby_${CA_STYLEGUIDE_VERSION_TAG}'
    command: wait-for-it --timeout=120 --strict ca-styleguide:6006 -- bundle exec rake design_system:all
    container_name: design-system-cucumber.test
    environment:
      - BRANCH_NAME
      - BROWSER
      - BROWSERSTACK_USERNAME
      - BROWSERSTACK_ACCESS_KEY
      - BROWSERSTACK_CONFIGURATION_OPTIONS
      - DOCKER_TAG
    env_file:
      - testing/grid_ci.env
    volumes:
      - ./testing/artifacts/reports:/app/testing/artifacts/reports
      - ./testing/artifacts/html_pages:/app/testing/artifacts/html_pages
      - ./testing/artifacts/screenshots:/app/testing/artifacts/screenshots
      - ./testing/artifacts/logs:/app/testing/artifacts/logs
    depends_on:
      - ca-styleguide
      - hub
      - node-chrome
      - node-firefox

  browserstack-cucumber:
    <<: *cucumber_default
    container_name: design-system-browserstack-cucumber.test
    env_file:
      - testing/browserstack_ci.env
    depends_on: []

  hub:
    image: selenium/hub:4.0.0-alpha-6-20200609
    container_name: design-system-hub.test
    env_file:
      - testing/grid_ci.env
    ports:
      - 4444:4444
    volumes:
      - ./:/app

  node-chrome: &node_default
    image: selenium/node-chrome:4.0.0-alpha-6-20200609
    container_name: design-system-node-chrome.test
    env_file:
      - testing/grid_ci.env
    shm_size: 1g
    volumes:
      - ./testing:/app
    environment:
      HUB_HOST: hub

  node-firefox:
    <<: *node_default
    image: selenium/node-firefox:4.0.0-alpha-6-20200609
    container_name: design-system-node-firefox.test
