version: '3.2'

services:
  ca-styleguide:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.ca-styleguide
      cache_from:
        - '979633842206.dkr.ecr.eu-west-1.amazonaws.com/design-system:dev_ca-styleguide_${CA_STYLEGUIDE_VERSION_TAG}'
        - '979633842206.dkr.ecr.eu-west-1.amazonaws.com/design-system:ca-styleguide'
    image: '979633842206.dkr.ecr.eu-west-1.amazonaws.com/design-system:dev_ca-styleguide_${CA_STYLEGUIDE_VERSION_TAG}'
    container_name: ca-styleguide.test
    command: npm run docs:serve
    hostname: ca-styleguide.test
    ports:
      - 6006:6006
    environment:
      - NODE_ENV=development

  visual-tests:
    image: 'backstopjs/backstopjs:${BACKSTOPJS_VERSION:-latest}'
    container_name: visual-tests.test
    # Default entrypoint is backstop, so the command just needs to be the arguments
    command: test --config=backstop-config-ci.js
    volumes:
      - ./testing/visual-regression:/src
    depends_on:
      - ca-styleguide

  wcag-tests:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.wcag
      cache_from:
        - '979633842206.dkr.ecr.eu-west-1.amazonaws.com/design-system:dev_wcag_${CA_STYLEGUIDE_VERSION_TAG}'
        - '979633842206.dkr.ecr.eu-west-1.amazonaws.com/design-system:wcag'
    image: '979633842206.dkr.ecr.eu-west-1.amazonaws.com/design-system:dev_wcag_${CA_STYLEGUIDE_VERSION_TAG}'
    container_name: wcag-tests.test
    command: pa11y-ci --config=/src/wcag/pa11yci.ci.js
    volumes:
      - ./testing:/src
    depends_on:
      - ca-styleguide

  cucumber: &cucumber_default
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.ruby_host
      cache_from:
        - '979633842206.dkr.ecr.eu-west-1.amazonaws.com/design-system:dev_ruby_${CA_STYLEGUIDE_VERSION_TAG}'
        - '979633842206.dkr.ecr.eu-west-1.amazonaws.com/design-system:ruby'
    image: '979633842206.dkr.ecr.eu-west-1.amazonaws.com/design-system:dev_ruby_${CA_STYLEGUIDE_VERSION_TAG}'
    command: bin/wait-for --timeout=120 ca-styleguide:6006 -- bundle exec rake design_system:all
    container_name: design-system-cucumber.test
    # Every key set here SHOULD be passed in at call-time
    # If the key is NOT passed in, it will default to being un-set (nil)
    environment:
      - BRANCH_NAME
      - BROWSER
      - BROWSERSTACK_USERNAME
      - BROWSERSTACK_ACCESS_KEY
      - BROWSERSTACK_CONFIGURATION_OPTIONS
      - DOCKER_TAG
    # Every key set in here should NOT be in the list above
    # Any key in this file that also exists in the list above will be overwritten
    # If the key is in the list above but not set, it will be nil!
    env_file:
      - testing/grid_ci.env
    volumes:
      - ./testing/artifacts:/app/testing/artifacts
    depends_on:
      - ca-styleguide
      - hub
      - node-chrome
      - node-firefox

  browserstack-cucumber:
    <<: *cucumber_default
    container_name: design-system-browserstack-cucumber.test
    env_file:
      - testing/browserstack_ci.env
    depends_on: []

  ruby-tests:
    <<: *cucumber_default
    container_name: design-system-ruby-tests.test
    command: sh
    environment: []
    env_file: []
    volumes: []

  hub:
    image: selenium/hub:4.0.0-alpha-6-20200609
    container_name: design-system-hub.test
    env_file:
      - testing/grid_ci.env
    ports:
      - 4444:4444
    volumes:
      - ./:/app

  node-chrome: &node_default
    image: selenium/node-chrome:4.0.0-alpha-6-20200609
    container_name: design-system-node-chrome.test
    env_file:
      - testing/grid_ci.env
    shm_size: 1g
    volumes:
      - ./testing:/app
    environment:
      HUB_HOST: hub

  node-firefox:
    <<: *node_default
    image: selenium/node-firefox:4.0.0-alpha-6-20200609
    container_name: design-system-node-firefox.test
