#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

echo_task() {
  printf "\033[0;34m--> %s\033[0m\n" "$*"
}

cd "$(dirname "$0")"

function setup_npm_package() {
  echo_task "Installing and setting up the npm package"
  npm install
}

function setup_engine() {
  echo_task "Installing Rails engine dependencies"
  pushd engine
  bundle install
  bundle exec appraisal install
  popd
}

function setup_demo_app() {
  echo_task "Setting up the demo app"
  pushd demo
  bundle install
  npm install
  bin/rails log:clear tmp:clear
  bin/rails restart
  popd
}

function setup_docs_website() {
  echo_task "Setting up the documentation website"
  pushd design-system-docs
  bundle install
  npm install
  popd
}

echo_task "Setting up Design System project"

setup_npm_package
setup_engine
setup_demo_app
setup_docs_website

echo_task "Set up complete!"
