inherit_gem:
  citizens-advice-style:
    - default.yml
    - default-rails.yml

require:
  - rubocop-rspec

Metrics/MethodLength:
  CountAsOne: ['array', 'hash']
  Exclude:
    # Previews often include lots of test data by design
    # so we're not too worried about method length there
    - 'previews/**/*.rb'

Metrics/BlockLength:
  Exclude:
    # Previews often include lots of test data by design
    # so we're not too worried about block length there
    - 'previews/**/*.rb'

Layout/LineLength:
  Exclude:
    # Previews often include lots of test data by design
    # so we're not too worried about line length there
    - 'previews/**/*.rb'

Metrics/ClassLength:
  CountAsOne: ['array', 'hash']

RSpec/ExampleLength:
  CountAsOne: ['array', 'hash']

# @FIXME
Rails/I18nLocaleAssignment:
  Exclude:
    - 'spec/components/citizens_advice_components/badge_spec.rb'
    - 'spec/components/citizens_advice_components/checkbox_group_spec.rb'
    - 'spec/components/citizens_advice_components/header_spec.rb'
    - 'spec/components/citizens_advice_components/input_spec.rb'
    - 'spec/components/citizens_advice_components/page_review_spec.rb'
    - 'spec/components/citizens_advice_components/pagination_spec.rb'
    - 'spec/components/citizens_advice_components/search_spec.rb'
    - 'spec/components/citizens_advice_components/targeted_content_spec.rb'
    - 'spec/spec_helper.rb'
