inherit_gem:
  citizens-advice-style:
    - default.yml
    - default-rails.yml

AllCops:
  SuggestExtensions: false
  # Match minimum target version to gemspec
  TargetRubyVersion: 3.2

Lint/MissingSuper:
  Exclude:
    # Calls to super in subclasses of ViewComponent::Base aren't needed
    # by default and can change the behaviour of **kwargs so we
    # exclude component classes from this rule
    # https://github.com/ViewComponent/view_component/discussions/1545
    - 'app/components/**/*'

Style/HashSyntax:
  # We do not necessarily find that Ruby 3.1’s hash value shorthand syntax
  # encourages greater readability so support either style
  EnforcedShorthandSyntax: 'either'

RSpec/ExampleLength:
  CountAsOne: ['array', 'hash']

Rails/RakeEnvironment:
  Exclude:
    # Gem Rakefile is not used in a Rails context
    - 'Rakefile'

RSpec/MultipleExpectations:
  Max: 4
  Exclude:
    # Feature tests deliberately use multiple expectations
    - 'spec/features/**/*.rb'
