inherit_gem:
  citizens-advice-style:
    - default.yml
    - default-rails.yml

require:
  - rubocop-rspec

AllCops:
  # Match minimum target version to gemspec
  TargetRubyVersion: 2.7

# Calls to super in subclasses of ViewComponent::Base aren't needed
# by default and can change the behaviour of **kwargs so we
# exclude component classes from this rule
# https://github.com/ViewComponent/view_component/discussions/1545
Lint/MissingSuper:
  Exclude:
    - 'app/components/**/*'

Metrics/MethodLength:
  CountAsOne: ['array', 'hash']

Metrics/ClassLength:
  CountAsOne: ['array', 'hash']

RSpec/ExampleLength:
  CountAsOne: ['array', 'hash']
