inherit_gem:
  citizens-advice-style:
    - default.yml
    - default-rails.yml

require:
  - rubocop-rspec

# Calls to super in subclasses of ViewComponent::Base aren't needed
# by default and can change the behaviour of **kwargs so we
# exclude component classes from this rule
# https://github.com/ViewComponent/view_component/discussions/1545
Lint/MissingSuper:
  Exclude:
    - 'app/components/**/*'

Metrics/MethodLength:
  CountAsOne: ['array', 'hash']

Metrics/ClassLength:
  CountAsOne: ['array', 'hash']

RSpec/ExampleLength:
  CountAsOne: ['array', 'hash']

# @FIXME
Rails/I18nLocaleAssignment:
  Exclude:
    - 'spec/components/citizens_advice_components/badge_spec.rb'
    - 'spec/components/citizens_advice_components/checkbox_group_spec.rb'
    - 'spec/components/citizens_advice_components/header_spec.rb'
    - 'spec/components/citizens_advice_components/input_spec.rb'
    - 'spec/components/citizens_advice_components/page_review_spec.rb'
    - 'spec/components/citizens_advice_components/pagination_spec.rb'
    - 'spec/components/citizens_advice_components/search_spec.rb'
    - 'spec/components/citizens_advice_components/targeted_content_spec.rb'
    - 'spec/spec_helper.rb'
