inherit_gem:
  citizens-advice-style:
    - default.yml
    - default-rails.yml

AllCops:
  SuggestExtensions: false
  # Match minimum target version to gemspec
  TargetRubyVersion: 3.2
  Exclude:
    # Ignore generated appraisal gemfiles
    - "gemfiles/*"

Style/HashSyntax:
  # We do not necessarily find that Ruby 3.1’s hash value shorthand syntax
  # encourages greater readability so support either style
  EnforcedShorthandSyntax: "either"

Metrics/ClassLength:
  Exclude:
    # Exists to delegate to other classes so is verbose
    - "app/helpers/citizens_advice_components/form_builder.rb"

Metrics/MethodLength:
  Exclude:
    # Implements form builder interfaces which often take many parameters
    - "app/lib/citizens_advice_components/elements/*.rb"
    - "app/helpers/citizens_advice_components/form_builder.rb"

Metrics/ParameterLists:
  # Prefer explicit parameters to compact interfaces
  Max: 8
  Exclude:
    # Implements form builder interfaces which often take many parameters
    - "app/lib/citizens_advice_components/elements/*.rb"
    - "app/helpers/citizens_advice_components/form_builder.rb"

RSpec/ExampleLength:
  Max: 12
  CountAsOne: ["array", "hash"]
  Exclude:
    # Feature tests deliberately use longer example blocks
    - "spec/features/**/*.rb"

RSpec/MultipleExpectations:
  Max: 3
  Exclude:
    # Feature tests deliberately use multiple expectations
    - "spec/features/**/*.rb"

RSpec/NestedGroups:
  Max: 4

Rails/RakeEnvironment:
  Exclude:
    # Gem Rakefile is not used in a Rails context
    - "Rakefile"
