# frozen_string_literal: true

# Test against active Rails versions (https://endoflife.date/rails)
# as well as any additional View Component versions

appraise "rails_7_2" do
  rails_version = "~> 7.2.0"
  gem "actionpack", rails_version
  gem "actionview", rails_version
  gem "activemodel", rails_version
  gem "activerecord", rails_version
  gem "activesupport", rails_version
  gem "railties", rails_version
end

appraise "rails_8_0" do
  rails_version = "~> 8.0.0"
  gem "actionpack", rails_version
  gem "actionview", rails_version
  gem "activemodel", rails_version
  gem "activerecord", rails_version
  gem "activesupport", rails_version
  gem "railties", rails_version
end

appraise "rails_8_1" do
  rails_version = "~> 8.1.0"
  gem "actionpack", rails_version
  gem "actionview", rails_version
  gem "activemodel", rails_version
  gem "activerecord", rails_version
  gem "activesupport", rails_version
  gem "railties", rails_version
end

appraise "rails_main" do
  gem "actionpack", github: "rails/rails", branch: "main"
  gem "actionview", github: "rails/rails", branch: "main"
  gem "activemodel", github: "rails/rails", branch: "main"
  gem "activerecord", github: "rails/rails", branch: "main"
  gem "activesupport", github: "rails/rails", branch: "main"
  gem "railties", github: "rails/rails", branch: "main"
end

# Explicitly test against previously supported view component version
# using the oldest supported Rails version. This can be removed when
# we drop support for view component 3.x
appraise "view_component_3" do
  rails_version = "~> 7.2.0"
  gem "actionpack", rails_version
  gem "actionview", rails_version
  gem "activemodel", rails_version
  gem "activerecord", rails_version
  gem "activesupport", rails_version
  gem "railties", rails_version

  gem "view_component", "~> 3.0.0"
end
