# frozen_string_literal: true

# Test against active Rails versions (https://endoflife.date/rails)
# as well as any additional View Component versions

appraise "rails_7_2" do
  rails_version = "~> 7.2.0"
  gem "actionpack", rails_version
  gem "actionview", rails_version
  gem "activemodel", rails_version
  gem "activerecord", rails_version
  gem "activesupport", rails_version
  gem "railties", rails_version
end

appraise "rails_8_0" do
  rails_version = "~> 8.0.0"
  gem "actionpack", rails_version
  gem "actionview", rails_version
  gem "activemodel", rails_version
  gem "activerecord", rails_version
  gem "activesupport", rails_version
  gem "railties", rails_version
end

appraise "view_component_4" do
  rails_version = "~> 8.0.0"
  gem "actionpack", rails_version
  gem "actionview", rails_version
  gem "activemodel", rails_version
  gem "activerecord", rails_version
  gem "activesupport", rails_version
  gem "railties", rails_version

  gem "view_component", "4.0.0"
end
