# frozen_string_literal: true

# Test against active Rails versions (https://endoflife.date/rails)

appraise "rails_8_0" do
  rails_version = "~> 8.0.0"
  gem "actionpack", rails_version
  gem "actionview", rails_version
  gem "activemodel", rails_version
  gem "activerecord", rails_version
  gem "activesupport", rails_version
  gem "railties", rails_version
end

appraise "rails_8_1" do
  rails_version = "~> 8.1.0"
  gem "actionpack", rails_version
  gem "actionview", rails_version
  gem "activemodel", rails_version
  gem "activerecord", rails_version
  gem "activesupport", rails_version
  gem "railties", rails_version
end
