# frozen_string_literal: true

source "https://rubygems.org"

gemspec

group :development, :test do
  gem "appraisal"
  gem "capybara"
  gem "citizens-advice-style", github: "citizensadvice/citizens-advice-style-ruby", tag: "v12.0.0"
  gem "erb_lint"
  gem "i18n-tasks"
  gem "rspec"
  gem "rspec-rails"
end
