# frozen_string_literal: true

source "https://rubygems.org"

gemspec

rails_version = ENV.fetch("RAILS_VERSION", "~> 7.2.0").to_s

# rubocop:disable Bundler/DuplicatedGem
if rails_version == "main"
  # Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
  git "https://github.com/rails/rails", ref: "main" do
    gem "actionpack"
    gem "activemodel"
    gem "railties"
  end
else
  gem "actionpack", rails_version
  gem "activemodel", rails_version
  gem "railties", rails_version
end
# rubocop:enable Bundler/DuplicatedGem

group :development, :test do
  # Can be removed when either a Rails 7.0.x patch is released
  # or we remove support for Rails 7.0.x whichever is sooner
  # (likely the latter as it is near EOL)
  # https://github.com/ruby-concurrency/concurrent-ruby/issues/1077
  gem "concurrent-ruby", "1.3.4"

  gem "citizens-advice-style",
      github: "citizensadvice/citizens-advice-style-ruby",
      tag: "v11.0.0"

  gem "capybara"
  gem "erb_lint"
  gem "i18n-tasks"
  gem "rspec"
  gem "rspec-rails"
end
