# frozen_string_literal: true

source "https://rubygems.org"

gemspec

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem "rails", ENV.fetch("RAILS_VERSION", "~> 6.1").to_s

group :development, :test do
  gem "citizens-advice-style",
      github: "citizensadvice/citizens-advice-style-ruby",
      tag: "v9.0.0"

  gem "capybara"
  gem "haml_lint"
  gem "i18n-tasks"
  gem "rspec"
  gem "rspec-rails"
  gem "rspec-snapshot", "~> 2.0"
  gem "rubocop-rails", require: false
  gem "rubocop-rspec", require: false
end
