# frozen_string_literal: true

begin
  require "bundler/setup"
rescue LoadError
  puts "You must `gem install bundler` and `bundle install` to run rake tasks"
end

require "bundler/gem_tasks"

require "rspec/core/rake_task"
RSpec::Core::RakeTask.new(:spec)

require "rubocop/rake_task"
RuboCop::RakeTask.new

desc "Run ERB Lint"
task :erblint do
  `erblint --lint-all`
end

task lint: %i[rubocop erblint]

task default: %i[spec lint]
