# frozen_string_literal: true

begin
  require "bundler/setup"
rescue LoadError
  puts "You must `gem install bundler` and `bundle install` to run rake tasks"
end

require "bundler/gem_tasks"

require "rspec/core/rake_task"
RSpec::Core::RakeTask.new(:spec)

require "rubocop/rake_task"
RuboCop::RakeTask.new

desc "Run ERB Lint"
task :erb_lint do
  system "erb_lint --lint-all"
end

desc "Sync fonts between npm source and engine"
task :sync_fonts do
  source_files = Dir["../assets/fonts/*"]
  dest_path = File.expand_path("./app/assets/fonts/citizens_advice_components/", __dir__)
  FileUtils.cp_r source_files, dest_path
end

task lint: %i[rubocop erb_lint]

task default: %i[spec lint]
