FROM ruby:2.6

# Needed for running bin/docker/waiter
RUN apt update -y && apt install jq -y && apt clean

RUN gem install bundler -v '2.1.4'

WORKDIR /app

COPY Gemfile Gemfile.lock /app/

RUN bundle install

RUN mkdir -p /app

COPY . /app
