FROM alekzonder/puppeteer:1

USER root

RUN apt-get update && apt-get install wait-for-it

RUN yarn global add pa11y-ci

ENV PATH "/usr/local/share/.config/yarn/global/node_modules/.bin/:${PATH}"

USER pptruser
