FROM alekzonder/puppeteer:1

USER root

RUN apt-get update && apt-get install wait-for-it

RUN yarn global add pa11y pa11y-ci

COPY ./scripts/update-pa11y-config.js ./scripts/wcag-tests.js .

ENV PATH "/usr/local/share/.config/yarn/global/node_modules/.bin/:${PATH}"

USER pptruser
