function componentUrl(urlPath) {
  return `http://localhost:3000/rails/view_components/citizens_advice_components/${urlPath}`;
}

module.exports = {
  defaults: {
    chromeLaunchConfig: {
      args: ['--no-sandbox'],
    },
    ignore: [
      // ignore missing anchor links in design-sytem
      'WCAG2AA.Principle2.Guideline2_4.2_4_1.G1,G123,G124.NoSuchId',
    ],
  },
  urls: [
    'http://localhost:3000/content-sample',
    componentUrl('asset_hyperlink/example'),
    componentUrl('breadcrumbs/collapsing'),
    componentUrl('breadcrumbs/long'),
    componentUrl('breadcrumbs/not_collapsing'),
    componentUrl('breadcrumbs/not_full_width'),
    componentUrl('breadcrumbs/not_on_current_page'),
    componentUrl('callout/adviser'),
    componentUrl('callout/example'),
    componentUrl('callout/important'),
    componentUrl('callout/nested'),
    componentUrl('callout/standard'),
    componentUrl('callout/variable_heading_levels'),
    componentUrl('contact_details/example'),
    componentUrl('footer/default'),
    componentUrl('footer/minimal'),
    componentUrl('header/full_example'),
    componentUrl('header/minimal'),
    componentUrl('header/with_custom_account_link'),
    componentUrl('header/with_custom_logo'),
    componentUrl('header/with_navigation'),
    componentUrl('input/additional_attributes'),
    componentUrl('input/basic'),
    componentUrl('input/error'),
    componentUrl('input/hint'),
    componentUrl('input/optional'),
    componentUrl('input/type'),
    componentUrl('navigation/example'),
    componentUrl('notice_banner/example'),
    componentUrl('page_review/example'),
    componentUrl('pagination/with_fifth_page'),
    componentUrl('pagination/with_first_page'),
    componentUrl('pagination/with_last_page'),
    componentUrl('pagination/with_second_page'),
    componentUrl('pagination/with_tenth_page'),
    componentUrl('radio_group/additional_attributes'),
    componentUrl('radio_group/basic'),
    componentUrl('radio_group/error'),
    componentUrl('radio_group/hint'),
    componentUrl('radio_group/inline'),
    componentUrl('radio_group/long'),
    componentUrl('radio_group/optional'),
    componentUrl('radio_group/small'),
    componentUrl('search/example'),
    componentUrl('search/with_value'),
    componentUrl('success_message/example'),
    componentUrl('table/example'),
    componentUrl('table/long_table'),
    componentUrl('table/no_caption'),
    componentUrl('targeted_content/adviser'),
    componentUrl('targeted_content/anchor'),
    componentUrl('targeted_content/default'),
    componentUrl('text_input/additional_attributes'),
    componentUrl('text_input/basic'),
    componentUrl('text_input/error'),
    componentUrl('text_input/fixed_widths'),
    componentUrl('text_input/hint'),
    componentUrl('text_input/optional'),
    componentUrl('text_input/type'),
    componentUrl('text_input/value'),
    componentUrl('textarea/additional_attributes'),
    componentUrl('textarea/basic'),
    componentUrl('textarea/error'),
    componentUrl('textarea/hint'),
    componentUrl('textarea/optional'),
    componentUrl('textarea/value'),
  ],
};
