# i18n-tasks finds and manages missing and unused translations: https://github.com/glebm/i18n-tasks
base_locale: en

# Read and write translations.
data:
  yaml:
    write:
      # do not wrap lines at 80 characters
      line_width: -1

# Find translate calls
# This previously used aliases to reduce duplication but
# that is broken in Ruby 3.1 until an upstream fix is released.
# https://github.com/glebm/i18n-tasks/pull/415
search:
  relative_paths:
    - 'app/components'
  paths:
    - 'app/components'
  relative_roots:
    - 'app/components'
