inherit_gem:
  citizens-advice-style:
    - default.yml
    - default-rails.yml

Lint/MissingSuper:
  Exclude:
    # Calls to super in subclasses of ViewComponent::Base aren't needed
    - 'app/components/**/*'

Metrics/MethodLength:
  CountAsOne: ['hash', 'array']

Metrics/ClassLength:
  Exclude:
    - spec/components/previews/**/*

Layout/LineLength:
  Exclude:
    - spec/components/previews/**/*

Rails/I18nLocaleTexts:
  Enabled: false
