# frozen_string_literal: true

source "https://rubygems.org"

ruby "2.7.4"

gem "high_voltage", "~> 3.1"
gem "puma", "~> 5.5"
gem "rails", "~> 7.0"
gem "webpacker", "~> 5.0"

gem "citizens_advice_components", path: "../engine"

group :development do
  gem "byebug", platforms: %i[mri mingw x64_mingw]
  gem "cypress-rails"
  gem "listen", "~> 3.2"
  gem "pry"
  gem "spring"
  gem "spring-watcher-listen", "~> 2.0.0"
  gem "web-console", ">= 3.3.0"
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]
