# frozen_string_literal: true

source "https://rubygems.org"

ruby "2.7.2"

gem "bootsnap", ">= 1.4.2", require: false
gem "puma", "~> 4.1"

gem "rails", "~> 6.0.3", ">= 6.0.3.4"

gem "design_system", path: "../engine"
gem "haml-rails"

gem "webpacker", "~> 5.0"

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem "byebug", platforms: %i[mri mingw x64_mingw]
end

group :test do
  gem "rspec-rails"
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem "listen", "~> 3.2"
  gem "spring"
  gem "spring-watcher-listen", "~> 2.0.0"
  gem "web-console", ">= 3.3.0"
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]
