---
EnableDefaultLinters: true
exclude:
  - "vendor/**/*"
  - "node_modules/**/*"
linters:
  ErbSafety:
    enabled: true
  AllowedScriptType:
    enabled: true
    allowed_types:
      - "module"
      - "text/javascript"
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      # Disable inherit_from rules which
      # aren't compatible with ERB templates.
      Layout/FirstArgumentIndentation:
        Enabled: false
      Layout/FirstArrayElementIndentation:
        Enabled: false
      Layout/InitialIndentation:
        Enabled: false
      Layout/LineLength:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Layout/TrailingWhitespace:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: false
      Style/FrozenStringLiteralComment:
        Enabled: false
