inherit_gem:
  citizens-advice-style:
    - default.yml
    - default-rails.yml

Metrics/BlockLength:
  Exclude:
    # Models use decant which is based on .define blocks
    - "app/models/*"

Rails/RakeEnvironment:
  Exclude:
    - "Rakefile"
