# frozen_string_literal: true

# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require_relative "config/application"

Rails.application.load_tasks

Rake::Task[:default].prerequisites.clear if Rake::Task.task_defined?(:default)

require "rubocop/rake_task"
RuboCop::RakeTask.new

desc "Run herb"
task :herb do
  system "herb analyze"
  system "herb lint"
end

task lint: %i[rubocop herb]

task default: %i[lint]
