name: Docs preview

on:
  pull_request:
    types:
      # Trigger when the pull request is labelled.
      # Used to only deploy previews when the "docs preview" label is added.
      - labeled
      # Trigger when an existing PR is updated.
      # Used to make sure new previews are deployed for changes after the label is added.
      - synchronize

jobs:
  # This job will:
  #   * deploy a draft every time there is a pull request created that has the expected label
  #   * comment on that pull request with the deploy URL
  docs-preview:
    name: Deploy docs preview to Netlify
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]' && github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'docs preview')
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version-file: .nvmrc

      # Setup docs site
      - uses: ruby/setup-ruby@4c56a21280b36d862b5fc31348f463d60bdc55d5
        with:
          ruby-version: "4.0.1"
          bundler-cache: true
          working-directory: website

      # Install dependencies
      - run: npm ci
        working-directory: website

      - run: ./bin/static-build
        working-directory: website

      - name: Deploy draft to Netlify
        uses: South-Paw/action-netlify-deploy@2e5ce944afb065f54453c5cc03291670687b454b
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
          build-dir: ./website/build
          draft: true
          comment-on-pull-request: true
          config-path: ./netlify.toml
