name: Design System Docs

on:
  pull_request:
    types:
      # Trigger when the pull request is labelled.
      # Used to only deploy previews when the "docs preview" label is added.
      - labeled
      # Trigger when an existing PR is updated.
      # Used to make sure new previews are deployed for changes after the label is added.
      - synchronize
  release:
    types:
      - created

jobs:
  # This job will:
  #   * deploy a draft every time there is a pull request created that has the expected label
  #   * comment on that pull request with the deploy URL
  deployPRDraft:
    name: Deploy draft to Netlify
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]' && github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'docs preview')
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      # Setup docs site
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.2'
          bundler-cache: true
          working-directory: website

      # Install dependencies
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: website

      - run: ./bin/static-build
        working-directory: website

      - name: Deploy draft to Netlify
        uses: South-Paw/action-netlify-deploy@v1.2.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
          build-dir: ./website/build
          draft: true
          comment-on-pull-request: true
          config-path: ./netlify.toml
