name: Design System Docs

on:
  pull_request:
    types:
      # Trigger when the pull request is labelled.
      # Used to only deploy previews when the "docs preview" label is added.
      - labeled
      # Trigger when an existing PR is updated.
      # Used to make sure new previews are deployed for changes after the label is added.
      - synchronize
  release:
    types:
      - created

jobs:
  # This job will:
  #   * deploy a draft every time there is a pull request created that has the expected label
  #   * comment on that pull request with the deploy URL
  deployPRDraft:
    name: Deploy draft to Netlify
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]' && github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'docs preview')
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      # We link the @citizensadvice/design-system package
      # from the root but we only build the lib/ directory
      # when we publish to npm, so we need to build it first.
      - uses: bahmutov/npm-install@v1
      - run: npm run build

      # Setup docs site
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.4'
          bundler-cache: true
          working-directory: design-system-docs

      # Yarn install
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: design-system-docs

      - run: ./bin/bridgetown deploy
        working-directory: design-system-docs

      - name: Deploy draft to Netlify
        uses: South-Paw/action-netlify-deploy@v1.2.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
          build-dir: ./design-system-docs/output
          draft: true
          comment-on-pull-request: true
          config-path: ./netlify.toml

  # This job will:
  #   * deploy a production build every time there is a release created
  #   * comment that commit with the deploy URL
  publishOnRelease:
    name: Publish release to Netlify
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'created'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      # We link the @citizensadvice/design-system package
      # from the root but we only build the lib/ directory
      # when we publish to npm, so we need to build it first.
      - uses: bahmutov/npm-install@v1
      - run: npm run build

      # Setup docs site
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.4'
          bundler-cache: true
          working-directory: design-system-docs

      # Yarn install
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: design-system-docs

      - run: ./bin/bridgetown deploy
        working-directory: design-system-docs

      - name: Deploy production to Netlify
        uses: South-Paw/action-netlify-deploy@v1.2.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
          build-dir: ./design-system-docs/output
          config-path: ./netlify.toml
          comment-on-commit: true
