name: Engine
on: [push]

jobs:
  ruby-test:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: engine
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
      - run: bundle exec rake spec
