name: Engine
on: [push]

jobs:
  ruby-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      # Cache and install npm dependencies using https://github.com/bahmutov/npm-install
      - uses: bahmutov/npm-install@v1
      - run: npm test
