name: Engine

on: workflow_call

jobs:
  engine-specs:
    name: Run engine specs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Active Ruby versions (https://endoflife.date/ruby)
        ruby_version: ['3.1', '3.2', '3.3']
        # Last 3 major Rails releases
        rails_version: ['~> 6.1', '~> 7.0.0', '~> 7.1.0']
        # Any supported ViewComponent versions
        view_component_version: ['~> 2.82', '~> 3']
    env:
      RAILS_VERSION: ${{ matrix.rails_version }}
      VIEW_COMPONENT_VERSION: ${{ matrix.view_component_version }}
    defaults:
      run:
        working-directory: engine
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          working-directory: engine
      - run: |
          bundle config path vendor/bundle
          bundle update
          bundle install --jobs 4 --retry 3
      - run: bundle exec rake spec

  engine-lint:
    name: Run engine lint checks
    needs: engine-specs
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: engine
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: '3.3.1'
          working-directory: engine
      - run: bundle exec rubocop --format progress --format github
      - run: bundle exec erblint --lint-all
