name: Engine
on: [push]

jobs:
  ruby-test:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: engine
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.2'
          working-directory: engine
      - run: |
          bundle config path vendor/bundle
          bundle update
          bundle install --jobs 4 --retry 3
      - run: bundle exec rake spec
