name: Push to main
on:
  push:
    branches:
      - main

jobs:
  tests:
    name: Run all tests
    uses: ./.github/workflows/tests.yml

  publish:
    name: Publish docs website to Netlify
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version-file: .nvmrc

      # Setup docs site
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4.5"
          bundler-cache: true
          working-directory: website

      # Install dependencies
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: website

      - run: ./bin/static-build
        working-directory: website

      - name: Deploy production to Netlify
        uses: South-Paw/action-netlify-deploy@v1.2.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
          build-dir: ./website/build
          config-path: ./netlify.toml
